import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',

    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                "surface": "#f8f9ff",
                "on-tertiary-fixed-variant": "#005236",
                "tertiary-fixed": "#6ffbbe",
                "on-error-container": "#93000a",
                "outline-variant": "#c7c4d8",
                "on-error": "#ffffff",
                "background": "#f8f9ff",
                "on-surface": "#0b1c30",
                "on-tertiary-container": "#67f4b7",
                "tertiary-fixed-dim": "#4edea3",
                "tertiary-container": "#006e4b",
                "on-background": "#0b1c30",
                "on-secondary-fixed-variant": "#004395",
                "on-surface-variant": "#464555",
                "secondary-fixed-dim": "#adc6ff",
                "primary-fixed-dim": "#c3c0ff",
                "on-primary-fixed-variant": "#3323cc",
                "inverse-surface": "#213145",
                "surface-container-low": "#eff4ff",
                "secondary-fixed": "#d8e2ff",
                "on-secondary-container": "#fefcff",
                "on-primary-fixed": "#0f0069",
                "outline": "#777587",
                "secondary-container": "#2170e4",
                "error": "#ba1a1a",
                "on-tertiary-fixed": "#002113",
                "on-primary-container": "#dad7ff",
                "surface-bright": "#f8f9ff",
                "primary": "#3525cd",
                "surface-tint": "#4d44e3",
                "surface-variant": "#d3e4fe",
                "primary-fixed": "#e2dfff",
                "error-container": "#ffdad6",
                "on-secondary-fixed": "#001a42",
                "primary-container": "#4f46e5",
                "on-primary": "#ffffff",
                "surface-container-highest": "#d3e4fe",
                "surface-container": "#e5eeff",
                "secondary": "#0058be",
                "inverse-on-surface": "#eaf1ff",
                "inverse-primary": "#c3c0ff",
                "surface-container-high": "#dce9ff",
                "tertiary": "#005338",
                "on-secondary": "#ffffff",
                "on-tertiary": "#ffffff",
                "surface-dim": "#cbdbf5",
                "surface-container-lowest": "#ffffff",
            },

            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },

            spacing: {
                "margin": "1.5rem",
                "space-lg": "1.5rem",
                "gutter-lg": "2rem",
                "margin-sm": "1rem",
                "gutter-sm": "1rem",
                "space-md": "1rem",
                "space-sm": "0.5rem",
                "space-xs": "0.25rem",
                "gutter": "1.5rem",
                "space-xl": "2rem",
                "margin-lg": "2rem",
            },

            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                "body-sm": ["Inter"],
                "body-md": ["Inter"],
                "body-lg": ["Inter"],
                "label-md": ["Inter"],
                "label-sm": ["Inter"],
                "label-xs": ["Inter"],
                "title-sm": ["Inter"],
                "headline-xl": ["Plus Jakarta Sans"],
                "headline-lg": ["Plus Jakarta Sans"],
                "headline-md": ["Plus Jakarta Sans"],
                "display-lg": ["Plus Jakarta Sans"],
            },

            fontSize: {
                "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
                "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
                "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
                "label-md": ["14px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "500" }],
                "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
                "label-xs": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
                "title-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
                "headline-xl": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
                "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
                "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
            },
        },
    },

    plugins: [forms],
};